### ISSUE TITLE
OBS Publishing Internals

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uwadmin#4]
OBS Publishing currently happens via https://github.com/Door43/tools/blob/master/uw/publish.sh.  That shell script mostly calls other Python scripts in that tools repository.

We probably want to integrate the Python scripts directly into this site.

**Comment by paltman** [comment]
@jag3773 can you elaborate what you mean by integrating into this site?

**Comment by paltman** [comment]
@jag3773 when you say integrate these scripts into this site do you mean have them as management commands that something like either crontab or some action in the website can execute?

**Comment by jag3773** [comment]
The primary point of this site is to allow an admin to publish a resource to our API.  So when I say integrate I mean that when an admin clicks on publish it should both create a DB entry and it should fire off all the scripts that actually publish the content to the API, which are referenced in that shell script.

**Comment by paltman** [comment]
@jag3773 got it. so currently there isn't a "publish" button but rather just updating the OBS record to have a publish date.

Should we change that so that the date is filled in with today's date when a Publish Button is pushed?  or should we support setting a publish date like we currently do and then only call the scripts if the date is today or in the past (and then have a management command that will run each day and check dates of things and publish if `published`date`==`now()` so people can set for things to be published in the future)?

**Comment by jag3773** [comment]
@paltman Yes, let's just have the publish button start the publishing right away.  I don't foresee a reason to want to schedule a publish action.

**Comment by paltman** [comment]
@jag3773 NOTE: this will require setting up redis and celery on the server
