### ISSUE TITLE
Table Style List for Pub/Track Info

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uwadmin#8]
The publishing and tracking information should be available in a table-style list, probably similar to http://td.unfoldingword.org/data-sources/ethnologue/country-codes/ so that sorting and searching can work easily.

Note that there will be several records for each language, they should show up in the table in reverse chronological order.

**Comment by paltman** [comment]
@jag3773 looks like i misinterpreted the data when merging in #13. I was thinking there was really only a single record per language but now that I review the modeling, it supports multiple per language just not sure it is doing it properly.  What's the purpose of multiple records? Recording a history of changes instead of just editing?

**Comment by dsm-git** [comment]
Exactly, history of changes.

**Comment by paltman** [comment]
![screenshot 2015-02-27 19 58 52](https://cloud.githubusercontent.com/assets/1192/6424272/2d6ae0fe-bebb-11e4-85be-747e86630d16.png)

Do you want all fields in the table or only some of them?

**Comment by paltman** [comment]
Updated to save a bit of space:

![screenshot 2015-02-27 20 05 20](https://cloud.githubusercontent.com/assets/1192/6424302/25a1e830-bebc-11e4-98a0-1c66e01e8cff.png)

**Comment by paltman** [comment]
![screenshot 2015-03-07 02 33 39](https://cloud.githubusercontent.com/assets/1192/6540702/68997944-c472-11e4-8181-d997fda3a4d0.png)

@jag3773 how's this for showing history of items?

**Comment by jag3773** [comment]
Fabulous.

**Comment by paltman** [comment]
I think to add the features of the "table style list" like on tD we will want to do it differently than using the js plugin there because of the way this data is multi-dimensional. My first instinct is to just implement standard paging and then implement search, but do these through normal Django rather than a JSON endpoint like the table js plugin requires.

**Comment by jag3773** [comment]
I like the screenshot that you posted in https://github.com/unfoldingWord-dev/uwadmin/issues/8#issuecomment-77679482.  Let's leave it like that for now.

**Comment by paltman** [comment]
So i'll just close this for now then and we can open a new one when the interface needs to change.
